Search by files content
Ukhanskyi/search_by_text_into_file pull request #1
Opened 2021-09-17 14:04 UTC by Ukhanskyi

![image](https://user-images.githubusercontent.com/27281528/133795872-4a986522-0912-446c-9030-2b392fa3d982.png)

![image](https://user-images.githubusercontent.com/27281528/133795995-2f5bda31-5915-40fa-9965-71384e482059.png)

2021-09-20 07:15 UTC, Hunter2065 reviewed
resolve some comments

2021-09-20 07:15 UTC, Hunter2065 commented on app/javascript/controllers/hello_controller.js
> +}
remove if you don't use it

2021-09-20 07:15 UTC, Hunter2065 commented on app/services/parse_document_service.rb
> +  def parse_text_from_doc
я думаю логічно, що метод parse_text, класу document, парсить тектс), неймінг класу та метода краще поправ)

2021-09-20 07:15 UTC, Hunter2065 commented on app/views/documents/index.html.erb
> +</div>
тут в тебе все свіже), заюзай слім)

2021-09-20 11:48 UTC, Ukhanskyi commented on app/javascript/controllers/hello_controller.js
> +}
ok)

2021-09-20 11:49 UTC, Ukhanskyi commented on app/services/parse_document_service.rb
> +  def parse_text_from_doc
гаразд

2021-09-20 12:41 UTC, Ukhanskyi commented on app/views/documents/index.html.erb
> +</div>
готово)

2021-09-21 09:52 UTC, igorkasyanchuk requested changes

2021-09-21 09:52 UTC, igorkasyanchuk commented on .gitignore
> +/public
чому? це нічо що там є ще інші файли які потрібні

2021-09-21 09:52 UTC, igorkasyanchuk commented on spec/rails_helper.rb
> +
а де тести? 
я бачу рубішник код, а де тести?

2021-09-21 20:05 UTC, Ukhanskyi commented on .gitignore
> +/public
виправив)

2021-09-21 20:05 UTC, Ukhanskyi commented on spec/rails_helper.rb
> +
вже написав

2021-09-30 09:23 UTC, merged